### ISSUE TITLE
JOSS review by Sherwood - Issue 1

### ISSUE THREAD

**Issue by csherwood-usgs** [TomasBeuzen/pybeach#1]
Some of the links in the README.md file are broken. Specifically, 404 errors from  the links to an example notebook and the documentation.

**Comment by TomasBeuzen** [comment]
Thanks for pointing these out - readme has now been updated.

**Comment by kbarnhart** [comment]
Just linking this with the [JOSS Review](https://github.com/openjournals/joss-reviews/issues/1890)
