### ISSUE TITLE
JOSS review by Chris Sherwood issue 2

### ISSUE THREAD

**Issue by csherwood-usgs** [TomasBeuzen/pybeach#2]
Unfortunately, PyBeach is also being used by a Python coding conference: https://2020.pybeach.org/. Not sure whether this is worth resolving or not.

**Comment by kbarnhart** [comment]
Just linking this with the [JOSS Review](https://github.com/openjournals/joss-reviews/issues/1890)

**Comment by TomasBeuzen** [comment]
Thanks for picking this up Chris - I notice that the pybeach conference has nothing to do with the coastal field or "beaches" but just occurs on the beach (lucky!). pybeach was also one of the only short, snappy and coastal-related package names available on pypi. As a result, I would like to keep the name pybeach for the package for now but will keep this conference in the back of mind.
