### ISSUE TITLE
JOSS review by Sherwood issue 4

### ISSUE THREAD

**Issue by csherwood-usgs** [TomasBeuzen/pybeach#4]
The short paper is very readable and seems to cover all of the points required by JOSS.  The examples showing performance of the various methods were nice, but I was left wondering "How is the true dune toe identified in the dataset?" A mention of how "true" dune toes are defined and determined from field observations or profiles would help.

**Comment by kbarnhart** [comment]
Just linking this with the [JOSS Review](https://github.com/openjournals/joss-reviews/issues/1890)

**Comment by TomasBeuzen** [comment]
Great question Chris, the true dune toes for each of the profiles used in pybeach was identified "manually" and quality checked by multiple people, multiple times (this extremely tedious process was what inspired the creation of the ML model in pybeach). In the [manuscript](https://github.com/TomasBeuzen/pybeach/blob/master/paper.md) I currently have the lines (128-129) "_For each dataset described above, the dune toe location was manually identified by an expert to facilitate the creation of the ML models._" Although I feel this perhaps doesn't do justice to the amount of time and effort that went into identifying the true dune toe. I've now expanded on this particular sentence a little more in the manuscript:

"_For each dataset described above, the true location of the dune toe on each indiviudal profile transect was manually identified and quality checked by *multiple* experts and verified using satelitte imagery, digital elevation models and/or in-situ observations where available. This resulted in the best possible data to facilitate the creation of the ML models in __*pybeach*__._"
