### ISSUE TITLE
JOSS review  by Sherwood - Final issue

### ISSUE THREAD

**Issue by csherwood-usgs** [TomasBeuzen/pybeach#5]
I have completed my review of this repo. Except for the missing link to the documentation, everything looks great. I have downloaded, installed, and tested the code, and read through many of the code and documentation files. The author has done a great job...the code is clean, the documentation thorough, and the software provides a valuable tool for those of use that work with beach morphology data. I plan to use the code for analysis of my data, and if I run in to any questions, I will raise additional issues. I recommend this software and the accompanying paper be published with minor revisions to address the issues raised here. Thanks for the opportunity to review this code.

**Comment by TomasBeuzen** [comment]
Hi Chris - thank you so much for taking the time and effort to review my submission. I really appreciate it! I will address the issues you raised in the next few days and will leave them open for the duration of the review process.

**Comment by kbarnhart** [comment]
Just linking this with the [JOSS Review](https://github.com/openjournals/joss-reviews/issues/1890)
