### ISSUE TITLE
Paper edits for JOSS

### ISSUE THREAD

**Issue by kbarnhart** [TomasBeuzen/pybeach#7]
This issue summarizes a few topical editor requests for the content of the paper [under review at JOSS](https://github.com/openjournals/joss-reviews/issues/1890). 

@TomasBeuzen can you 

- [x] Provide a very short definition of "beach" and "dune" in the context of shore profile geometry. I request this to make the summary more understandable for a diverse, non-specialist audience. 
 
- [x] Specify you are using the Random Forest classifier in the summary rather than referring to the more general "Machine Learning". I think this may be as simple as stating "Machine learning using Random Forest classification- discussed further below." in your enumerated list of supported methods. 

- [x] When you are discussing support for custom ML models from user supplied data, can you be more specific about which ML methods are supported. Random forest with other data? Anything SciKit-learn supports?

- [x] Your paper nicely describes your extensive work to compare the performance of the alternative methods provided in **pybeach**. However, this is lost a bit in the **pybeach** section. I'd recommend that you add a new section heading called something like "Performance Assessment" just before the sentences that start with "For each dataset described above, the true location of the dune toe..."

**Comment by TomasBeuzen** [comment]
Thank you @kbarnhart for your great comments - all have now been addressed! To be clear:

1. New text has been added to briefly clarify to non-specialist audiences the "beach" and "dune": _"Sandy coastlines typically comprise two key parts: a beach and dune. The beach is the section of sandy coast that is mostly above water (depending upon tide) and actively influenced by waves, while dunes are elevated mounds/ridges of sand at the back of the beach. The interface between the beach and dune is often characterised by a distinct change in ground slope (with the dune having a steeper slope than the beach)."_

2. Have now referred to "Machine learning using Random Forest classification" as per your suggestion.

3. Have now clarified that pybeach supports any scikit-learn model that supports probabilistic prediction.

4. Have added a new section heading "Performance assessment" at the appropriate location.
